name: 'Build gatsby-project-kb site'

on:
  push:
    branches:
      - master
      - ci
      - feature/deploy

jobs:
  build:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: "14.15.0"
      
      - name: yarn install
        uses: jaid/action-npm-install@v1.2.4
      - run: node --version
      - run: gatsby --version
      - name: build
        uses: CultureHQ/actions-yarn@master
        env:
          KB_BASE_PATH: '/gatsby-project-kb'
        with:
          args: build

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: demo/public
        env:
          GITHUB_TOKEN: ${{ secrets.GATSBY_PROJECT_KB_TOKEN }}
